/**
 * Danh sách quốc gia và vùng lãnh thổ trên thế giới (theo ISO 3166-1).
 * Việt Nam đặt đầu danh sách; các quốc gia còn lại xếp theo thứ tự A–Z (tên tiếng Anh/Việt).
 */
export const DANH_SACH_QUOC_GIA: string[] = [
  'Việt Nam',
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua và Barbuda',
  'Argentina',
  'Armenia',
  'Úc',
  'Áo',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Bỉ',
  'Belize',
  'Bénin',
  'Bhutan',
  'Bolivia',
  'Bosnia và Herzegovina',
  'Botswana',
  'Brasil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Campuchia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Trung Phi',
  'Tchad',
  'Chile',
  'Trung Quốc',
  'Colombia',
  'Comoros',
  'Congo',
  'Costa Rica',
  'Bờ Biển Ngà',
  'Croatia',
  'Cuba',
  'Síp',
  'Cộng hòa Séc',
  'Đan Mạch',
  'Djibouti',
  'Dominica',
  'Cộng hòa Dominicana',
  'Ecuador',
  'Ai Cập',
  'El Salvador',
  'Guinea Xích Đạo',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Phần Lan',
  'Pháp',
  'Gabon',
  'Gambia',
  'Gruzia',
  'Đức',
  'Ghana',
  'Hy Lạp',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'Ấn Độ',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Ý',
  'Jamaica',
  'Nhật Bản',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Triều Tiên',
  'Hàn Quốc',
  'Kuwait',
  'Kyrgyzstan',
  'Lào',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Quần đảo Marshall',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mông Cổ',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Hà Lan',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Bắc Macedonia',
  'Na Uy',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Ba Lan',
  'Bồ Đào Nha',
  'Qatar',
  'Romania',
  'Nga',
  'Rwanda',
  'Saint Kitts và Nevis',
  'Saint Lucia',
  'Saint Vincent và Grenadines',
  'Samoa',
  'San Marino',
  'São Tomé và Príncipe',
  'Ả Rập Xê Út',
  'Sénégal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Quần đảo Solomon',
  'Somalia',
  'Nam Phi',
  'Nam Sudan',
  'Tây Ban Nha',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Thụy Điển',
  'Thụy Sĩ',
  'Syria',
  'Đài Loan',
  'Tajikistan',
  'Tanzania',
  'Thái Lan',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad và Tobago',
  'Tunisia',
  'Thổ Nhĩ Kỳ',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraina',
  'Các Tiểu vương quốc Ả Rập Thống nhất',
  'Vương quốc Anh',
  'Hoa Kỳ',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican',
  'Venezuela',
  'Yemen',
  'Zambia',
  'Zimbabwe',
]
