/**
 * Danh sách 34 tỉnh, thành phố trực thuộc trung ương Việt Nam sau sáp nhập
 * (Nghị quyết 202/2025/QH15, có hiệu lực từ 01/7/2025).
 * Thứ tự: 6 thành phố trước (A–Z), sau đó 28 tỉnh (A–Z).
 */
export const DANH_SACH_TINH_THANH_VIET_NAM: string[] = [
  // Thành phố trực thuộc trung ương (theo ABC)
  'Thành phố Cần Thơ',
  'Thành phố Đà Nẵng',
  'Thành phố Hà Nội',
  'Thành phố Hải Phòng',
  'Thành phố Hồ Chí Minh',
  'Thành phố Huế',
  // Tỉnh (theo ABC)
  'An Giang',
  'Bắc Ninh',
  'Cà Mau',
  'Cao Bằng',
  'Đắk Lắk',
  'Điện Biên',
  'Đồng Nai',
  'Đồng Tháp',
  'Gia Lai',
  'Hà Tĩnh',
  'Hưng Yên',
  'Khánh Hòa',
  'Lai Châu',
  'Lào Cai',
  'Lạng Sơn',
  'Lâm Đồng',
  'Nghệ An',
  'Ninh Bình',
  'Phú Thọ',
  'Quảng Ninh',
  'Quảng Ngãi',
  'Quảng Trị',
  'Sơn La',
  'Tây Ninh',
  'Thanh Hóa',
  'Thái Nguyên',
  'Tuyên Quang',
  'Vĩnh Long',
]

/** Mã tỉnh/thành theo API v2 (provinces.open-api.vn/api/v2) — dữ liệu sau sáp nhập 07/2025. */
export const MA_TINH_THEO_TEN: Record<string, string> = {
  'Thành phố Cần Thơ': '92',
  'Thành phố Đà Nẵng': '48',
  'Thành phố Hà Nội': '01',
  'Thành phố Hải Phòng': '31',
  'Thành phố Hồ Chí Minh': '79',
  'Thành phố Huế': '46',
  'An Giang': '91',
  'Bắc Ninh': '24',
  'Cà Mau': '96',
  'Cao Bằng': '04',
  'Đắk Lắk': '66',
  'Điện Biên': '11',
  'Đồng Nai': '75',
  'Đồng Tháp': '82',
  'Gia Lai': '52',
  'Hà Tĩnh': '42',
  'Hưng Yên': '33',
  'Khánh Hòa': '56',
  'Lai Châu': '12',
  'Lào Cai': '15',
  'Lạng Sơn': '20',
  'Lâm Đồng': '68',
  'Nghệ An': '40',
  'Ninh Bình': '37',
  'Phú Thọ': '25',
  'Quảng Ninh': '22',
  'Quảng Ngãi': '51',
  'Quảng Trị': '44',
  'Sơn La': '14',
  'Tây Ninh': '80',
  'Thanh Hóa': '38',
  'Thái Nguyên': '19',
  'Tuyên Quang': '08',
  'Vĩnh Long': '86',
}
